spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/feature4
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect